### ISSUE TITLE
Handling @namespace and using SUIT/BEM

### ISSUE THREAD

**Issue by simonsmith** [ileri/postcss-bem#2]
Interesting plugin. Was wondering if there are any plans to allow this to output BEM as well as SUIT (which it currently does). Right now it's probably quicker to just use normal selectors but with the ability to choose BEM or SUIT I could see that being quite useful.

Also, does this collide with the `@namespace` at rule in CSS? - https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace ?

**Comment by ileri** [comment]
Oh, you're right about the `@namespace` rule, I'll change that. And I was already planning to implement BEM. I'll do that soon.

**Comment by simonsmith** [comment]
Great, thanks!
